### ISSUE TITLE
REQ: Better EDDN error when at a outpost without commodities market.

### ISSUE THREAD

**Issue by wolverine2710** [Andargor/edce-client#12]
Noticed it before but forgot to mention it. I've cleared my save and started at an outpost without a market. Running EDCE 1..0.9 shows the following error: EDCE: Error: EDDN postMarketData FAIL submit error

You might want to consider changing that into a more descriptive message.

**Comment by AnthorNet** [comment]
Hey,
Can you provide your last.json, we will looked into it ;)

**Comment by wolverine2710** [comment]
I don't see an option to upload a (JSON) file. I will send it to your private email address.

**Comment by AnthorNet** [comment]
Can you try last version ?

**Comment by wolverine2710** [comment]
It now show the following msg:
EDCE: Error: EDDN postMarketData FAIL station must have a market

Much better ;-)  Thanks for the quick fix, 
I knew what was causing it, others might be at a loss ;-)
