### ISSUE TITLE
REQ: --version and --help flag.

### ISSUE THREAD

**Issue by wolverine2710** [Andargor/edce-client#13]
When toying around with multiple EDCE versions it would be great to have a --version flag so it possible to check which version I'm running. It would also give the casual user the possibility to check if he/she is running the latest version of EDCE.

A --help flag would also be nice for some explanation about the tool.

Note: Hoping that the author of the pull request for a library friendly version will add some examples soon(ish).

**Comment by wolverine2710** [comment]
Just detected that in edce/global.py there is a version variable. Don't think most casual users would find that....

**Comment by Andargor** [comment]
Better late than never: version flag implemented in the client, and the help is just a usage summary. For the library, actual help for developers would actually mean commenting the code, which I may do eventually, just not right now :)
