### ISSUE TITLE
missing commodity in convertCommodityEDDN

### ISSUE THREAD

**Issue by seringue** [Andargor/edce-client#3]
```
if name == 'Terrain Enrichment Systems':
    return 'Land Enrichment Systems'

if name == 'Agricultural Medicines':
    return 'Agri-Medicines'

if name == 'Heliostatic Furnaces':
    return 'Microbial Furnaces'
```

also there is a drone commodity wich has "NonMarketable" in categoryName, i guess this is for future implementation.

**Comment by seringue** [comment]
sorry for not editing the files directly, I have to get more used to python and github before that

**Comment by Andargor** [comment]
Fixed. If you learn to make pull requests, you name will appear as a contributor :)
