### ISSUE TITLE
JSON dump - problems when commander name got accents

### ISSUE THREAD

**Issue by gbiobob** [Andargor/edce-client#5]
Inside the generated .xz log file, there is problem with accented characters in commander name field 
"é" become "\u00e9"
Maybe there is problem when the .xz is created (missing an utf8 encoding ?)

**Comment by Andargor** [comment]
It's definitely an encoding issue, that is standard JSON way of handling non-ASCII. Is your commander willing to share his last.json? Please have him send it to me by email.

**Comment by gbiobob** [comment]
I got the archive not the last.json,
do you need it also ?

2015-05-07 15:26 GMT+02:00 Andargor notifications@github.com:

**Comment by Andargor** [comment]
Can your friend pull the latest and give it a whirl?

**Comment by gbiobob** [comment]
I just ask him, send you the results asap.

**Comment by Andargor** [comment]
Is this issue and Issue #6 resolved?

**Comment by gbiobob** [comment]
Will got an answer monday for the issue #6, I just know his archive filename still have an accent.

**Comment by Andargor** [comment]
I had changed the utf8 handling to convert the escape sequence "\u..." to the actual characters, so if his log has filenames such as "edce-Vanité-LTT 14436-20150507143509.xz", then that is normal. Also the commander name should be now without escapes in the JSON.

**Comment by gbiobob** [comment]
On the last file Cmdr Vanité send to me there is always a problem inside the file with his Cmdr name.

Edit : just check last file submitted to edboard, all seem to be ok inside the file, I'll ask him to send me back his last file to be sure.

**Comment by Andargor** [comment]
Be aware that if you are processing the JSON, the library you are using might escape utf8. The only way to be sure is to look at the last.json and the file in a log archive using 7-zip.

**Comment by gbiobob** [comment]
I got the last files from Cmdr Vanité,
The issue is half resolved :
inside the .xz I confirm all is now ok : thanks !
inside the last.json there is always "Vanit\u00e9" (not a problem for me, I don't use this file).

**Comment by Andargor** [comment]
I think I fixed it! I fed your friend's JSON with the escape sequence, and the last.json had the "é" instead of the escape sequence. Please confirm.

**Comment by gbiobob** [comment]
Cmdr Vanité just test the last release,
- the xz content is ok
- the last.json is ok

NB there is one last encoding problem in the Window console when he launch the player_dump.py (he discovered it today) `CMDR:                                   VanitÃ©`
Not a big problem, for me you can close the issue.

**Comment by Andargor** [comment]
I opened Issue #7 for the Windows encoding problem, so that we don't forget it in case some other people have the issue later. Marking this one as resolved.
